### ISSUE TITLE
[Bug] Error while changing progress

### ISSUE THREAD

**Issue by v-amorim** [AzuredBlue/mpv-anilist-updater#1]
Hi! The script works great on another series, but with this one, it locates the entry with "Open Anilist" but fails to update it.

Any ideas on what could be causing this?

![{C27A38DB-1C0A-4FCA-9E78-49FAD23DF556}](https://github.com/user-attachments/assets/c21d0be0-b815-4eac-9657-7c25896df7e4)

**Comment by AzuredBlue** [comment]
> Any ideas on what could be causing this?

Hey, sorry for the late reply, apparently I don't have notifications for this

There could be 2 reasons:
1 - You haven't set it to "watching" or "planning" on your AL
2 - The API request didnt find it

However, it seems to be able to find it with the same search as the title
![image](https://github.com/user-attachments/assets/b2cb49ca-2347-4f9d-89f9-c9dff5476de0)

Kyou no Asuka show seems to have an episode duration of 3 minutes, this should only be an issue if the show has more than 1 season and it has to fetch all, so in theory it should work

Make sure its set to "watching" or "planning", if it still doesn't work, try sending here the full name of the file

**Comment by v-amorim** [comment]
I binge watched the entire series in that day (since it was short), had to manually change progress, no idea as to why it didn't work.
