### ISSUE TITLE
Add scanning of folder names

### ISSUE THREAD

**Issue by ghost** [AzuredBlue/mpv-anilist-updater#2]
I have a folder /mnt/portable/Anime/3_gatsu no Lion/ where all the files are titled. Is it possible to get the anime name from the folder instead?
```
10.mp4  12.mp4  14.mp4  16.mp4  18.mp4  1.mp4   21.mp4  2.mp4  4.mp4  6.mp4  8.mp4
11.mp4  13.mp4  15.mp4  17.mp4  19.mp4  20.mp4  22.mp4  3.mp4  5.mp4  7.mp4  9.mp4
```
Btw this script works great. Thank you for making it

**Comment by AzuredBlue** [comment]
For now, it should work with the folder that contains it

If theres 3 layers (e. g 3_gatsu_ no Lion/S2/2.mp4) then it wont work

You can go ahead and close the issue if it works properly now

**Comment by pinknoseboopy** [comment]
> For now, it should work with the folder that contains it
> 
> You can go ahead and close the issue if it works properly now

Yes thank you, this works perfectly. I was wondering if it would also be possible to add another exception, getting the season and episode ie S01E03-"Let's Play Rich Poor Man!".mkv from the file, but getting the anime title itself from the folder "Fruits Basket S01-S03". This would work for instances where each season was put into the same folder. 
Note that in this example, all animes are set to watching.
```
[anilistUpdater] File name guess: MatchesDict({'season': 1, 'episode': 3, 'title': "Let's Play Rich Man-Poor Man!", 'crc32': 'ACEAC1F5', 'container': 'mkv', 'mimetype': 'video/x-matroska', 'type': 'episode'})
[anilistUpdater] 2. Folder guess: MatchesDict({'title': 'Fruits Basket', 'season': 1, 'screen_size': '1080p', 'other': ['Dual Audio', 'Rip'], 'source': 'Blu-ray', 'color_depth': '10-bit', 'audio_codec': 'Dolby Digital', 'video_codec': 'H.265', 'release_group': 'EMBER', 'type': 'episode'})
[anilistUpdater] Guessed name: Fruits Basket
[anilistUpdater] {'id': 120, 'title': {'romaji': 'Fruits Basket'}, 'season': 'SUMMER', 'seasonYear': 2001, 'episodes': 26, 'format': 'TV', 'duration': 24, 'status': 'FINISHED', 'mediaListEntry': None}
[anilistUpdater] ERROR: 'NoneType' object is not subscriptable
[anilistUpdater] File name guess: MatchesDict({'season': 1, 'episode': 3, 'title': "Let's Play Rich Man-Poor Man!", 'crc32': 'ACEAC1F5', 'container': 'mkv', 'mimetype': 'video/x-matroska', 'type': 'episode'})
[anilistUpdater] 2. Folder guess: MatchesDict({'title': 'Fruits Basket', 'season': 1, 'screen_size': '1080p', 'other': ['Dual Audio', 'Rip'], 'source': 'Blu-ray', 'color_depth': '10-bit', 'audio_codec': 'Dolby Digital', 'video_codec': 'H.265', 'release_group': 'EMBER', 'type': 'episode'})
[anilistUpdater] Guessed name: Fruits Basket
[anilistUpdater] {'id': 120, 'title': {'romaji': 'Fruits Basket'}, 'season': 'SUMMER', 'seasonYear': 2001, 'episodes': 26, 'format': 'TV', 'duration': 24, 'status': 'FINISHED', 'mediaListEntry': None}
[anilistUpdater] ERROR: 'NoneType' object is not subscriptable
Saving state.
AV: 00:00:07 / 00:23:52 (1%) A-V:  0.000 Cache: 133s/25MB
Exiting... (Quit)
```

Thank you

**Comment by AzuredBlue** [comment]
> > For now, it should work with the folder that contains it
> > You can go ahead and close the issue if it works properly now
> 
> Yes thank you, this works perfectly. I was wondering if it would also be possible to add another exception, getting the season and episode ie S01E03-"Let's Play Rich Poor Man!".mkv from the file, but getting the anime title itself from the folder "Fruits Basket S01-S03". This would work for instances where each season was put into the same folder. Note that in this example, all animes are set to watching.
> 
> ```
> [anilistUpdater] File name guess: MatchesDict({'season': 1, 'episode': 3, 'title': "Let's Play Rich Man-Poor Man!", 'crc32': 'ACEAC1F5', 'container': 'mkv', 'mimetype': 'video/x-matroska', 'type': 'episode'})
> [anilistUpdater] 2. Folder guess: MatchesDict({'title': 'Fruits Basket', 'season': 1, 'screen_size': '1080p', 'other': ['Dual Audio', 'Rip'], 'source': 'Blu-ray', 'color_depth': '10-bit', 'audio_codec': 'Dolby Digital', 'video_codec': 'H.265', 'release_group': 'EMBER', 'type': 'episode'})
> [anilistUpdater] Guessed name: Fruits Basket
> [anilistUpdater] {'id': 120, 'title': {'romaji': 'Fruits Basket'}, 'season': 'SUMMER', 'seasonYear': 2001, 'episodes': 26, 'format': 'TV', 'duration': 24, 'status': 'FINISHED', 'mediaListEntry': None}
> [anilistUpdater] ERROR: 'NoneType' object is not subscriptable
> [anilistUpdater] File name guess: MatchesDict({'season': 1, 'episode': 3, 'title': "Let's Play Rich Man-Poor Man!", 'crc32': 'ACEAC1F5', 'container': 'mkv', 'mimetype': 'video/x-matroska', 'type': 'episode'})
> [anilistUpdater] 2. Folder guess: MatchesDict({'title': 'Fruits Basket', 'season': 1, 'screen_size': '1080p', 'other': ['Dual Audio', 'Rip'], 'source': 'Blu-ray', 'color_depth': '10-bit', 'audio_codec': 'Dolby Digital', 'video_codec': 'H.265', 'release_group': 'EMBER', 'type': 'episode'})
> [anilistUpdater] Guessed name: Fruits Basket
> [anilistUpdater] {'id': 120, 'title': {'romaji': 'Fruits Basket'}, 'season': 'SUMMER', 'seasonYear': 2001, 'episodes': 26, 'format': 'TV', 'duration': 24, 'status': 'FINISHED', 'mediaListEntry': None}
> [anilistUpdater] ERROR: 'NoneType' object is not subscriptable
> Saving state.
> AV: 00:00:07 / 00:23:52 (1%) A-V:  0.000 Cache: 133s/25MB
> Exiting... (Quit)
> ```
> 
> Thank you

Could you explain more what you mean? Do you mean prioritising the season from the file name instead of the folder name? Because that's how it should currently work unless I messed something up

Also that `'mediaListEntry': None` means it hasn't found that entry in your list

Anyways I'll take a look later
